spring:
  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

server:
  port: ${DEV_APP_INTERNAL_PORT}

app:
  base-url: ${DEV_APP_BASE_URL}
  short-url-base-url: ${DEV_SHORT_URL_BASE_URL}
  admin:
    login: ${DEV_ADMIN_LOGIN}
    password: ${DEV_ADMIN_PASSWORD}
    display-name: ${DEV_ADMIN_DISPLAY_NAME}
  jwt:
    secret: ${DEV_JWT_SECRET}
    access-expiration-minutes: ${DEV_JWT_ACCESS_EXPIRATION_MINUTES}
    refresh-expiration-days: ${DEV_JWT_REFRESH_EXPIRATION_DAYS}
  cookie:
    access-token-name: ${DEV_COOKIE_ACCESS_TOKEN_NAME}
    refresh-token-name: ${DEV_COOKIE_REFRESH_TOKEN_NAME}
    secure: ${DEV_COOKIE_SECURE}
    same-site: ${DEV_COOKIE_SAME_SITE}
    domain: ${DEV_COOKIE_DOMAIN}
  cors:
    allowed-origins: ${DEV_CORS_ALLOWED_ORIGINS}
  forwarded:
    proto-header: ${DEV_FORWARDED_PROTO_HEADER}
    host-header: ${DEV_FORWARDED_HOST_HEADER}
    port-header: ${DEV_FORWARDED_PORT_HEADER}
